import torch

def init():
    global PARAM
    PARAM = {
        'model_data_name': 'MNIST',
        'train_data_name': 'MNIST',
        'test_data_name': 'MNIST',
        'model_dir': 'mnist',
        'model_name': 'vade',
        'resume_TAG': '',
        'special_TAG': '',
        'optimizer_name': 'Adam',
        'scheduler_name': 'ReduceLROnPlateau',
        'lr': 1e-3,
        'milestones': [10,20,50,100],
        'threshold': 1,
        'threshold_mode': 'abs',
        'factor': 0.5,
        'normalize': False,
        'batch_size': [100,500],
        'num_workers': 0,
        'data_size': 0,
        'device': 'cpu',
        'activation': 'relu',
        'max_num_epochs': 100,
        'save_mode': 0,
        'world_size': 1,
        'train_metric_names': ['psnr','cluster_acc'],
        'test_metric_names': ['psnr','cluster_acc'],
        'topk': 1,
        'init_seed': 0,
        'num_Experiments': 1,
        'tuning_param': {'compression': 1, 'classification': 1},
        'loss_mode': {'compression':'bce','classification':'ce'},
        'num_level': 2,
        'code_size': 10,
        'num_iter': 16,
        'init_param_mode': 'gmm',
        'resume_mode': 0,
    }
